import { z } from "zod";
export const SolicitudSchema=z.object({solicitud_id:z.string(),solicitante:z.string(),proveedor_nombre:z.string(),proveedor_nit:z.string().optional(),descripcion:z.string(),centro_costo:z.string(),subarea:z.string(),cantidad:z.number(),valor_unitario:z.number(),valor_total:z.number(),moneda:z.enum(["COP","USD"]),indicador_iva:z.string().optional(),condiciones_pago:z.string().optional(),fecha_solicitud:z.string()});
export type Solicitud=z.infer<typeof SolicitudSchema>;
export type Paquete={correo:{id:string;de:string;asunto:string;fecha:string};solicitud:Solicitud;cotizacion:{referencia:string|null;proveedor:string;nit:string|null;total:number;moneda:string;validez_hasta:string|null;texto:string}|null;aprobacion:{de:string;fecha:string;aprobado:boolean;texto:string}|null;factura:{numero:string;fecha:string;total:number}|null};
export type Issue={codigo:string;detalle:string};
export type Derivados={proveedor_nit?:string;indicador_iva?:string;condiciones_pago?:string};
export type Validacion={apta:boolean;bloqueos:Issue[];confirmaciones:Issue[];derivados:Derivados;retroactiva:boolean};
export const OrdenCompraSchema=z.object({referencia:z.object({solicitud_id:z.string(),correo_id:z.string(),cotizacion_ref:z.string().nullable()}),sociedad:z.literal("1000"),organizacion_compras:z.literal("1000"),proveedor:z.object({codigo_sap:z.string(),nit:z.string(),nombre:z.string()}),moneda:z.enum(["COP","USD"]),condiciones_pago:z.string(),aprobador:z.object({email:z.string(),fecha_aprobacion:z.string(),evidencia_sha256:z.string()}),posiciones:z.array(z.object({numero:z.number(),descripcion:z.string().max(40),cantidad:z.number(),unidad:z.enum(["UN","H","MES"]),precio_unitario:z.number(),centro_costo:z.string(),subarea:z.string(),indicador_iva:z.string()})),excepciones:z.array(z.object({codigo:z.string(),detalle:z.string(),confirmado_por:z.string().nullable()}))});
export type OrdenCompra=z.infer<typeof OrdenCompraSchema>;
